name: pocket_mentor
description: Replace mindless scrolling with productive learning.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.2

  # HTTP & Networking
  dio: ^5.4.3
  connectivity_plus: ^6.0.3

  # Local Storage
  shared_preferences: ^2.2.3

  # File Picking
  file_picker: ^8.0.7

  # UI
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0

  # Utils
  intl: ^0.19.0

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
